const express = require("express");
const path = require("path");
const { Octokit } = require("@octokit/rest");
const { createAppAuth } = require("@octokit/auth-app");
const axios = require("axios");
require("dotenv").config();

const app = express();
app.use(express.json());
app.use(express.static(__dirname));

const APP_ID = process.env.GITHUB_APP_ID;
const PRIVATE_KEY = process.env.GITHUB_PRIVATE_KEY?.replace(/\\n/g, '\n');
const AI_URL = process.env.PYTHON_URL?.replace(/\/$/, "").trim();

function getOcto(installationId) {
    if (!APP_ID || !PRIVATE_KEY) throw new Error("GitHub App credentials missing in Environment Variables");
    return new Octokit({
        authStrategy: createAppAuth,
        auth: { appId: APP_ID, privateKey: PRIVATE_KEY, installationId }
    });
}

app.get("/", (req, res) => res.sendFile(path.join(__dirname, "index.html")));

app.post("/scan", async (req, res) => {
    try {
        const { repo, installation_id } = req.body;
        if (!repo || !installation_id) return res.status(400).json({ error: "Missing repo or installation_id" });
        if (!AI_URL) return res.status(500).json({ error: "PYTHON_URL not configured" });

        const [owner, repoName] = repo.split("/");
        const octo = getOcto(installation_id);

        const { data: tree } = await octo.git.getTree({
            owner, repo: repoName, tree_sha: 'main', recursive: true
        });

        const files = tree.tree.filter(f => f.type === 'blob').map(f => f.path);
        const ai = await axios.post(`${AI_URL}/analyze`, { repo, files }, { timeout: 20000 });
        
        res.json(ai.data);
    } catch (err) {
        console.error("❌ SCAN ERROR:", err.message);
        res.status(500).json({ error: err.message });
    }
});

app.post("/apply-fix", async (req, res) => {
    try {
        const { repo, installation_id, target_file } = req.body;
        if (!target_file || target_file === "undefined") throw new Error("Invalid target file. Please scan again.");

        const [owner, repoName] = repo.split("/");
        const octo = getOcto(installation_id);

        // 1. Get SHA & Original Content (Prevents 409 Conflict)
        const { data: fileData } = await octo.repos.getContent({ owner, repo: repoName, path: target_file });
        const originalCode = Buffer.from(fileData.content, 'base64').toString();

        // 2. Get AI Fix from Python Engine
        const aiResponse = await axios.post(`${AI_URL}/get-fix`, { file_path: target_file, original_code: originalCode });
        if (!aiResponse.data.fixed_code) throw new Error("AI Engine failed to return fixed_code");

        // 3. Create Unique Branch
        const branchName = `minion-fix-${Date.now()}`;
        const { data: mainRef } = await octo.git.getRef({ owner, repo: repoName, ref: 'heads/main' });
        await octo.git.createRef({ owner, repo: repoName, ref: `refs/heads/${branchName}`, sha: mainRef.object.sha });

        // 4. Update File using SHA
        await octo.repos.createOrUpdateFileContents({
            owner, repo: repoName, path: target_file,
            message: `🛡️ Minion SRE: Optimized ${target_file}`,
            content: Buffer.from(aiResponse.data.fixed_code).toString("base64"),
            branch: branchName, 
            sha: fileData.sha 
        });

        // 5. Create Pull Request
        const pr = await octo.pulls.create({
            owner, repo: repoName, 
            title: `🛡️ AI SRE Fix: ${target_file}`,
            head: branchName, base: 'main', 
            body: "This is an automated fix generated by Minion SRE Agent. Please review and merge."
        });

        res.json({ pr_url: pr.data.html_url });
    } catch (err) {
        console.error("❌ FIX ERROR:", err.response?.data || err.message);
        res.status(500).json({ error: err.message });
    }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`🚀 Orchestrator active on port ${PORT}`));