const express = require("express");
const path = require("path");
const { Octokit } = require("@octokit/rest");
const { createAppAuth } = require("@octokit/auth-app");
const axios = require("axios");
require("dotenv").config();

const app = express();
app.use(express.json());
app.use(express.static(__dirname));

// Environment Variables
const APP_ID = process.env.GITHUB_APP_ID;
const PRIVATE_KEY = process.env.GITHUB_PRIVATE_KEY?.replace(/\\n/g, '\n');

// 🛡️ URL FIX: Trim spaces and remove trailing slash to prevent "Invalid URL" error
const rawAiUrl = process.env.AI_ENGINE_URL || "";
const AI_URL = rawAiUrl.replace(/\/$/, "").trim();

function getOcto(installationId) {
    if (!APP_ID || !PRIVATE_KEY) {
        throw new Error("GITHUB_APP_ID or GITHUB_PRIVATE_KEY is missing in env");
    }
    return new Octokit({
        authStrategy: createAppAuth,
        auth: { appId: APP_ID, privateKey: PRIVATE_KEY, installationId }
    });
}

app.get("/", (req, res) => res.sendFile(path.join(__dirname, "index.html")));

app.post("/scan", async (req, res) => {
    try {
        const { repo, installation_id } = req.body;
        
        // Validation Checks
        if (!repo || !installation_id) throw new Error("Credentials or Repo path missing");
        if (!AI_URL) throw new Error("AI_ENGINE_URL is not configured on Render");
        if (!repo.includes("/")) throw new Error("Invalid repo format. Must be 'owner/repo'");

        const [owner, repoName] = repo.split("/");
        const octo = getOcto(installation_id);

        console.log(`>> Scanning: ${owner}/${repoName}`);
        
        // Recursive tree fetch
        const { data: tree } = await octo.git.getTree({
            owner, repo: repoName, tree_sha: 'main', recursive: true
        });

        const files = tree.tree.filter(f => f.type === 'blob').map(f => f.path);
        
        // 🚀 Calling AI Engine with full error tracking
        console.log(`>> Connecting to AI: ${AI_URL}/analyze`);
        const ai = await axios.post(`${AI_URL}/analyze`, { repo, files }, { timeout: 30000 });
        
        res.json(ai.data);
    } catch (err) {
        // Detailed logging for Render logs
        console.error("❌ SCAN ERROR:", err.response?.data || err.message);
        res.status(500).json({ 
            error: err.message, 
            details: err.response?.data || "Check AI Engine status" 
        });
    }
});

app.post("/apply-fix", async (req, res) => {
    try {
        const { repo, installation_id, target_file } = req.body;
        if (!target_file) throw new Error("No target file provided for fix");

        const [owner, repoName] = repo.split("/");
        const octo = getOcto(installation_id);

        // 1. Get current content
        const { data: fileData } = await octo.repos.getContent({ owner, repo: repoName, path: target_file });
        const originalCode = Buffer.from(fileData.content, 'base64').toString();

        // 2. Request fix from AI
        console.log(`>> Fetching fix for: ${target_file}`);
        const aiResponse = await axios.post(`${AI_URL}/get-fix`, { 
            file_path: target_file, 
            original_code: originalCode 
        });

        // 3. Create branch and commit
        const branch = `ai-fix-${Date.now()}`;
        const { data: main } = await octo.git.getRef({ owner, repo: repoName, ref: 'heads/main' });
        await octo.git.createRef({ owner, repo: repoName, ref: `refs/heads/${branch}`, sha: main.object.sha });

        // Ensure fixed_code is treated as string
        const fixedContent = typeof aiResponse.data.fixed_code === 'string' 
            ? aiResponse.data.fixed_code 
            : JSON.stringify(aiResponse.data.fixed_code, null, 2);

        await octo.repos.createOrUpdateFileContents({
            owner, repo: repoName, path: target_file,
            message: "🤖 AI SRE Fix",
            content: Buffer.from(fixedContent).toString("base64"),
            branch, 
            sha: fileData.sha
        });

        // 4. Create Pull Request
        const pr = await octo.pulls.create({
            owner, repo: repoName, title: `🛡️ AI Fix: ${target_file}`,
            head: branch, base: 'main', 
            body: "Automated fix generated by Minion SRE. Review the code changes before merging."
        });

        res.json({ pr_url: pr.data.html_url });
    } catch (err) {
        console.error("❌ FIX ERROR:", err.response?.data || err.message);
        res.status(500).json({ error: err.message });
    }
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`🚀 Orchestrator running on port ${PORT}`));