const express = require("express");
const path = require("path");
const { Octokit } = require("@octokit/rest");
const { createAppAuth } = require("@octokit/auth-app");
const axios = require("axios");
require("dotenv").config();

const app = express();
app.use(express.json());
app.use(express.static(__dirname));

const APP_ID = process.env.GITHUB_APP_ID;
const PRIVATE_KEY = process.env.GITHUB_PRIVATE_KEY?.replace(/\\n/g, '\n');
const AI_URL = process.env.AI_ENGINE_URL?.replace(/\/$/, "");

function getOcto(installationId) {
    return new Octokit({
        authStrategy: createAppAuth,
        auth: { appId: APP_ID, privateKey: PRIVATE_KEY, installationId }
    });
}

app.get("/", (req, res) => res.sendFile(path.join(__dirname, "index.html")));

app.post("/scan", async (req, res) => {
    try {
        const { repo, installation_id } = req.body;
        if (!repo || !installation_id) throw new Error("Credentials missing");

        const [owner, repoName] = repo.split("/");
        const octo = getOcto(installation_id);

        const { data: tree } = await octo.git.getTree({
            owner, repo: repoName, tree_sha: 'main', recursive: true
        });

        const files = tree.tree.filter(f => f.type === 'blob').map(f => f.path);
        const ai = await axios.post(`${AI_URL}/analyze`, { repo, files });
        res.json(ai.data);
    } catch (err) {
        console.error(err.message);
        res.status(500).json({ error: "Scan failed" });
    }
});

app.post("/apply-fix", async (req, res) => {
    try {
        const { repo, installation_id, target_file } = req.body;
        const [owner, repoName] = repo.split("/");
        const octo = getOcto(installation_id);

        const { data: fileData } = await octo.repos.getContent({ owner, repo: repoName, path: target_file });
        const originalCode = Buffer.from(fileData.content, 'base64').toString();

        const aiResponse = await axios.post(`${AI_URL}/get-fix`, { 
            file_path: target_file, original_code: originalCode 
        });

        const branch = `ai-fix-${Date.now()}`;
        const { data: main } = await octo.git.getRef({ owner, repo: repoName, ref: 'heads/main' });
        await octo.git.createRef({ owner, repo: repoName, ref: `refs/heads/${branch}`, sha: main.object.sha });

        await octo.repos.createOrUpdateFileContents({
            owner, repo: repoName, path: target_file,
            message: "🤖 AI SRE Fix",
            content: Buffer.from(aiResponse.data.fixed_code).toString("base64"),
            branch, sha: fileData.sha
        });

        const pr = await octo.pulls.create({
            owner, repo: repoName, title: `🛡️ AI Fix: ${target_file}`,
            head: branch, base: 'main', body: "Automated fix generated by Minion SRE."
        });

        res.json({ pr_url: pr.data.html_url });
    } catch (err) {
        res.status(500).json({ error: err.message });
    }
});

app.listen(process.env.PORT || 3000);